### ISSUE TITLE
Problem with hilbert for small amplitude signals

### ISSUE THREAD

**Issue by celine-alameda** [gjmvanboxtel/gsignal#4]
Hi,

When used with a small amplitude signal (around 10^-10), hilbert does not return what is expected.

Example :

# behaves as expected
test1  = sin(1:100 * 0.1)
plot(test1)
plot(abs(gsignal::hilbert(test1)))

# does not behave as expected
test2 = 10^-9 * sin(1:100 * 0.1)
plot(test2)
plot(abs(gsignal::hilbert(test2)))

**Comment by gjmvanboxtel** [comment]
Hi,

Thanks for this report. The problem turned out to be a consequence of a numerical precision issue in the function ifft(). This has been fixed in the development version 0.3.3.9000 that you can install from Github, and will appear in the next version on CRAN in due time (I suspect that similar precision errors exists in a few other functions that I want to test thoroughly first).

Hope this helps,
Geert
